CREATE TABLE  IF NOT EXIST users(
	id SERIAL PRIMARY KEY,
	username VARCHAR(255) UNIQUE NOT NULL,
	name VARCHAR(255),
	email VARCHAR(255) UNIQUE NOT NULL,
	age INT,
	password_digest TEXT NOT NULL,
	genres VARCHAR(255)
);

CREATE TABLE IF NOT EXIST movies(
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	imdb_id VARCHAR(255) UNIQUE NOT NULL,
);

CREATE TABLE IF NOT EXIST series(
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	imdb_id VARCHAR(255) UNIQUE NOT NULL,
);

CREATE TABLE IF NOT EXIST episodes(
	id SERIAL PRIMARY KEY,
	title VARCHAR(255) NOT NULL,
	imdb_id VARCHAR(255) UNIQUE NOT NULL,
	series_id INT NOT NULL REFERENCES series(imdb_id)
);


CREATE TABLE IF NOT EXIST user_movies(
	id SERIAL PRIMARY KEY,
	user_id INT,
	movie_id INT,
	ratings INT
);

CREATE TABLE IF NOT EXIST user_series(
	id SERIAL PRIMARY KEY,
	user_id INT,
	series_id INT,
	ratings INT
);


CREATE TABLE IF NOT EXIST user_episodes(
	id SERIAL PRIMARY KEY,
	user_id INT,
	episode_id INT,
	ratings INT
);
